version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: 
          command: |
            cd project
            sudo apt-get install terraform
      
          
