version: 2.1
jobs:
  build:
    docker:
     - image: ubuntu
     - image: hashicorp/terraform:light
    working_directory: ~/home
    steps:
      - checkout
      - run: 
          name: sample
          command: |
            mkdir project
            cd project
      - run:
          name: dir
          command: ls
      - run:
          name: terraform install
          command: |
            terraform init

      
          
