version: 2.1
jobs:
  build:
    docker:
     - image: ubuntu
    working_directory: ~/home
    steps:
      - checkout
      - run: 
          name: sample
          command: |
            cd home

      
          
