version: 2.1
jobs:
  build:
    docker:
     - image: ubuntu
     - image: hashicorp/terraform:light
    working_directory: ~/home
    steps:
      - checkout
      - run: 
          name: sample
          command: |
            mkdir project
            cd project
      - run:
          name: dir
          command: |
             ls
             cd test
             bash wel.sh
        - run:
            name: terraform init
            command: terraform init
            