version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu
        working_directory: ~/example
    steps:
      - checkout
      - run: 
        name: terraform init
        command: |
          source $BASH_ENV
          mkdir terra
          cd terra
          terraform init

      
          
