version: 2.1
references:

base_image: &base_image
  ubuntu

working_directory: &working_directory
  ~/test

default_config: &default_config
  docker:
    - image: *base_image
  working_directory: *working_directory
  environment:
BASH_ENV: /root/.bashrc

jobs:
  build:
    <<: *default_config
    steps:
      - checkout
      - run: 
        name: terraform init
        command: |
          mkdir terra
          cd terra
          terraform init

      
          
