version: 2.1
orbs:
    hello: circleci/hello-build@0.0.5
workflows:
    "Hello Workflow":
        jobs:
          - hello/hello-build
        jobs:
          build:
            docker:
              - image: account-id.dkr.ecr.us-east-1.amazonaws.com/org/repo:0.1
                aws_auth:
                  aws_access_key_id: $AWS_ACCESS_KEY_ID
                  aws_secret_access_key: $EAWS_SECRECT_ACCESS_KEY